npm install -g /opt/homebrew/lib
npm install -g bash-language-server@3.0.5
npm install -g eslint@8.21.0
npm install -g heroku@7.60.2
npm install -g live-server@1.2.2
npm install -g nodemon@2.0.19
npm install -g npm@8.15.0
npm install -g pyright@1.1.264
npm install -g tls-test@0.0.1
npm install -g typescript-language-server@0.11.2
npm install -g typescript@4.7.4
npm install -g vscode-langservers-extracted@4.4.0
